# Generated by Django 5.0 on 2025-10-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='state',
        ),
    ]
