# Generated by Django 5.1.3 on 2025-09-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="upvote",
            field=models.IntegerField(default=0),
        ),
    ]
