# Generated by Django 5.1.3 on 2025-09-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_upvotes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Upvotes",
        ),
    ]
