# Generated by Django 5.1.3 on 2025-09-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_delete_upvotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Petition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("movieTitle", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("votes", models.IntegerField(default=0)),
            ],
        ),
    ]
